package uz.developers.appwarehouse.config;

import com.google.common.collect.Sets;

import java.util.Set;

import static uz.developers.appwarehouse.config.UserPermission.*;

public enum UserRole {


    OPERATOR(Sets.newHashSet(ATTACHMENT_READ_ALL,ATTACHMENT_READ_ONE,ATTACHMENT_ADD,
            CATEGORY_READ_ALL,CATEGORY_READ_ONE,CATEGORY_ADD,
            CLIENT_READ_ALL,CLIENT_READ_ONE,CLIENT_ADD,
            CURRENCY_READ_ALL,CURRENCY_READ_ONE,CURRENCY_ADD,
            INPUT_READ_ALL,INPUT_READ_ONE,INPUT_ADD,
            INPUTPRODUCT_READ_ALL,INPUTPRODUCT_READ_ONE,INPUTPRODUCT_ADD,
            MEASUREMENT_READ_ALL,MEASUREMENT_READ_ONE,MEASUREMENT_ADD,
            OUTPUT_READ_ALL,OUTPUT_READ_ONE,OUTPUT_ADD,
            OUTPUTPRODUCT_READ_ALL,OUTPUTPRODUCT_READ_ONE,OUTPUTPRODUCT_ADD,
            PRODUCT_READ_ALL,PRODUCT_READ_ONE,PRODUCT_ADD,
            SUPPLIER_READ_ALL,SUPPLIER_READ_ONE,SUPPLIER_ADD,
            WAREHOUSE_READ_ALL,WAREHOUSE_READ_ONE,WAREHOUSE_ADD,
            USER_READ_ALL,USER_READ_ONE,USER_ADD)),


    MODERATOR(Sets.newHashSet(ATTACHMENT_READ_ALL,ATTACHMENT_READ_ONE,ATTACHMENT_ADD,ATTACHMENT_EDIT,
            CATEGORY_READ_ALL,CATEGORY_READ_ONE,CATEGORY_ADD,CATEGORY_EDIT,
            CLIENT_READ_ALL,CLIENT_READ_ONE,CLIENT_ADD,CLIENT_EDIT,
            CURRENCY_READ_ALL,CURRENCY_READ_ONE,CURRENCY_ADD,CURRENCY_EDIT,
            INPUT_READ_ALL,INPUT_READ_ONE,INPUT_ADD,INPUT_EDIT,
            INPUTPRODUCT_READ_ALL,INPUTPRODUCT_READ_ONE,INPUTPRODUCT_ADD,INPUTPRODUCT_EDIT,
            MEASUREMENT_READ_ALL,MEASUREMENT_READ_ONE,MEASUREMENT_ADD,MEASUREMENT_EDIT,
            OUTPUT_READ_ALL,OUTPUT_READ_ONE,OUTPUT_ADD,OUTPUT_EDIT,
            OUTPUTPRODUCT_READ_ALL,OUTPUTPRODUCT_READ_ONE,OUTPUTPRODUCT_ADD,OUTPUTPRODUCT_EDIT,
            PRODUCT_READ_ALL,PRODUCT_READ_ONE,PRODUCT_ADD,PRODUCT_EDIT,
            SUPPLIER_READ_ALL,SUPPLIER_READ_ONE,SUPPLIER_ADD,SUPPLIER_EDIT,
            WAREHOUSE_READ_ALL,WAREHOUSE_READ_ONE,WAREHOUSE_ADD,WAREHOUSE_EDIT,
            USER_READ_ALL,USER_READ_ONE,USER_ADD,USER_EDIT)),


    SUPER_ADMIN(Sets.newHashSet(ATTACHMENT_READ_ALL,ATTACHMENT_READ_ONE,ATTACHMENT_ADD,ATTACHMENT_EDIT,ATTACHMENT_DELETE,
            CATEGORY_READ_ALL,CATEGORY_READ_ONE,CATEGORY_ADD,CATEGORY_EDIT,CATEGORY_DELETE,
            CLIENT_READ_ALL,CLIENT_READ_ONE,CLIENT_ADD,CLIENT_EDIT,CLIENT_DELETE,
            CURRENCY_READ_ALL,CURRENCY_READ_ONE,CURRENCY_ADD,CURRENCY_EDIT,CURRENCY_DELETE,
            INPUT_READ_ALL,INPUT_READ_ONE,INPUT_ADD,INPUT_EDIT,INPUT_DELETE,
            INPUTPRODUCT_READ_ALL,INPUTPRODUCT_READ_ONE,INPUTPRODUCT_ADD,INPUTPRODUCT_EDIT,INPUTPRODUCT_DELETE,
            MEASUREMENT_READ_ALL,MEASUREMENT_READ_ONE,MEASUREMENT_ADD,MEASUREMENT_EDIT,MEASUREMENT_DELETE,
            OUTPUT_READ_ALL,OUTPUT_READ_ONE,OUTPUT_ADD,OUTPUT_EDIT,OUTPUT_DELETE,
            OUTPUTPRODUCT_READ_ALL,OUTPUTPRODUCT_READ_ONE,OUTPUTPRODUCT_ADD,OUTPUTPRODUCT_EDIT,OUTPUTPRODUCT_DELETE,
            PRODUCT_READ_ALL,PRODUCT_READ_ONE,PRODUCT_ADD,PRODUCT_EDIT,PRODUCT_DELETE,
            SUPPLIER_READ_ALL,SUPPLIER_READ_ONE,SUPPLIER_ADD,SUPPLIER_EDIT,SUPPLIER_DELETE,
            WAREHOUSE_READ_ALL,WAREHOUSE_READ_ONE,WAREHOUSE_ADD,WAREHOUSE_EDIT,WAREHOUSE_DELETE,
            USER_READ_ALL,USER_READ_ONE,USER_ADD,USER_EDIT,USER_DELETE));


    private final Set<UserPermission> permissions;

    UserRole(Set<UserPermission> permissions) {
        this.permissions = permissions;
    }

    public Set<UserPermission> getPermissions() {
        return permissions;
    }

}
